import numpy as np
import pandas as pd
import json
import re

# TO Do:
##BB: After each round, output should say, Duke went for X, duke was 10% of prize pool, new estimtaed is X with weighting Y, Original is Z with weighting K, blended is B
#AAA: Figure out why inputting exact fair value CHANGES the estimate, print out new estimated pot, print out total sales and total percentage, maybe make sure percentages all add up to 100? That could be it...   
# 1. Change growth method to have a better estimate
# 2. Decide how to output the fair values, estimated pots, and ranges
# 3. Decide how to weigh the initial pot with the new estimated pot, and slowly reduce the weighting of the initial pot
# 4.         do this by using the percentage fair share / 100 done so far in the auction to weight the new estimate         


class CalcuttaAuction:
    def __init__(self, past_pots, champ_odds, second_place_odds, final_four_odds, elite_eight_odds, sweet_sixteen_odds, round_32_odds, round_32_vig, team_seeds, odds_type, auction_results):
        """
        Initialize the auction system.
        :param past_pots: List of total prize pools from the last 4 years.
        :param champ_odds: Dictionary of American odds for teams to win the championship.
        :param second_place_odds: Dictionary of American odds for teams to reach the championship game.
        :param final_four_odds: Dictionary of American odds for teams to reach the Final Four.
        :param elite_eight_odds: Dictionary of American odds for teams to reach the Elite Eight.
        :param sweet_sixteen_odds: Dictionary of American odds for teams to reach the Sweet Sixteen.
        :param round_32_odds: Dictionary of American odds for teams to reach the Round of 32.
        :param round_32_vig: The vig adjustment for Round of 32 odds.
        :param team_seeds: Dictionary mapping teams to their seed numbers.
        :param odds_type: The type of odds used in the input data (e.g., "american", "percentage").
        """
        self.past_pots = past_pots
        self.estimated_pot = 200000
        self.original_pot = self.estimated_pot  # Store original estimate
        self.last_pot = self.estimated_pot  # Store last round's estimate
        self.auction_results = auction_results
        self.team_seeds = team_seeds
        self.odds_type = odds_type
        
        # Convert odds and remove vig
        self.champ_odds = self.devig_odds(champ_odds, expected_total=1)
        self.second_place_odds = self.devig_odds(second_place_odds, expected_total=2)
        self.final_four_odds = self.devig_odds(final_four_odds, expected_total=4)
        self.elite_eight_odds = self.devig_odds(elite_eight_odds, expected_total=8)
        self.sweet_sixteen_odds = self.devig_odds(sweet_sixteen_odds, expected_total=16)
        self.round_32_odds = self.round_32_devig(round_32_odds, specified_vig=round_32_vig)
        
        # Generate team probabilities
        self.odds_dict = self.generate_team_odds()

        print(f"Initial estimated pot: ${self.estimated_pot:,.0f}")
        print("")

    def estimate_pot_growth(self):
        """Estimate the total prize pool based on past growth trends."""
        growth_rates = [self.past_pots[i] / self.past_pots[i - 1] for i in range(1, len(self.past_pots))]
        avg_growth = np.mean(growth_rates)
        return self.past_pots[-1] * avg_growth  # Projected pool based on average growth
    
    def devig_odds(self, odds_dict, expected_total):
        if self.odds_type == "percentage":
            total_prob = sum(odds_dict.values())/100
            adj_factor = total_prob / expected_total
            return {team: odds/100 / adj_factor for team, odds in odds_dict.items()}
        else:
            """Convert American odds to probabilities and remove vig based on expected number of teams per round."""
            probabilities = {team: self.american_to_prob(odds) for team, odds in odds_dict.items()}
            total_prob = sum(probabilities.values())
            
            adj_factor = total_prob / expected_total  # Adjust based on expected number of teams
            return {team: prob / adj_factor for team, prob in probabilities.items()}
    
    def round_32_devig(self, odds_dict, specified_vig):
        if self.odds_type == "percentage":
            print("Using percentage odds. No vig adjustment.")
            print("")
            return {team: odds / 100 for team, odds in odds_dict.items()}
        else:
            """Convert American odds to probabilities and remove vig based on specified vig."""
            probabilities = {team: self.american_to_prob(odds) for team, odds in odds_dict.items()}
            total_prob = sum(probabilities.values())
            
            adj_factor = 1 + specified_vig
            return {team: prob / adj_factor for team, prob in probabilities.items()}

    
    def american_to_prob(self, odds):
        if self.odds_type == "percentage":
            return odds / 100
        else:
            return abs(odds) / (abs(odds) + 100) if odds < 0 else 100 / (odds + 100)

    def generate_team_odds(self):
        """Generate per-round probabilities for each team."""
        odds_dict = {}
        for team in self.champ_odds:
            odds_dict[team] = [
                self.round_32_odds[team],
                self.sweet_sixteen_odds[team],
                self.elite_eight_odds[team],
                self.final_four_odds[team],
                self.second_place_odds[team],
                self.champ_odds[team]
            ]
        print(f"Data Checks:")
        print(f"Sum of round 32 odds: {round(sum([odds[0] for odds in odds_dict.values()]),4)}")
        print(f"Sum of sweet sixteen odds: {round(sum([odds[1] for odds in odds_dict.values()]),4)}")
        print(f"Sum of elite eight odds: {round(sum([odds[2] for odds in odds_dict.values()]),4)}")
        print(f"Sum of final four odds: {round(sum([odds[3] for odds in odds_dict.values()]),4)}")
        print(f"Sum of second place odds: {round(sum([odds[4] for odds in odds_dict.values()]),4)}")
        print(f"Sum of championship odds: {round(sum([odds[5] for odds in odds_dict.values()]),4)}")

        return odds_dict
    
    def calculate_fair_value(self):
        adjusted_pot = self.estimated_pot * .97
        #print(f"Adjusted pot: ${adjusted_pot:,.0f}")

        seed_bonus_counter = 0

        payout_percentages = [0.0075, 0.015, 0.0225, 0.035, 0.06, 0.08] #incremental values, since multiplying by probability for team to reach this round and summing
        fair_values = {}
        for team, odds in self.odds_dict.items():
            if team not in self.team_seeds:
                print(f"Warning: No seed found for team {team}")
            else:
                seed = self.team_seeds[team]
                seed_str = str(seed)
            
                team_fair_share = sum(prob * pct for prob, pct in zip(odds, payout_percentages)) * 0.97
                if len(self.auction_results) == 0:
                    fair_values[f"{team} ({seed_str})"] = team_fair_share * self.estimated_pot
                else:
                    fair_values[team] = team_fair_share * self.estimated_pot
        
                # Apply bonus for 13-16 seeds
            
                if self.team_seeds.get(team) >= 13:
                    seed_bonus_counter += 1
                    team_fair_share += 0.03 / 16
                    if len(self.auction_results) == 0:
                        fair_values[f"{team} ({seed_str})"] += round((0.03 / 16) * self.estimated_pot, 2)
                    else:
                        fair_values[team] += round((0.03 / 16) * self.estimated_pot, 2)

                #print(f"Team: {team}, Fair Percentage: {round(team_fair_share*100,5)}")

        if seed_bonus_counter != 16:
            raise ValueError(f"warning: seed bonus counter is {seed_bonus_counter}, not 16")

        fair_values = dict(sorted(fair_values.items(), key=lambda item: item[1], reverse=True))
        
        print(f"Fair values as % of pool, must be 1:  {round(sum(fair_values.values())/self.estimated_pot,4)}")
        if len(self.auction_results) == 0:
            print("Data Checks Complete")
        print("")
        return fair_values
    
    def update_pot(self, team, sale_price):
        if team not in self.odds_dict:
            print("Error: Team not found in odds dictionary.")
            return
        
        fair_share_sum = 0
        self.auction_results[team] = sale_price
        total_sales = sum(self.auction_results.values())

        self.last_pot = self.estimated_pot  # Store previous estimate before change
        
        payout_percentages = [0.0075, 0.015, 0.0225, 0.035, 0.06, 0.08]
        team_fair_share_dict = {team: .97* sum(prob * pct for prob, pct in zip(odds, payout_percentages)) for team, odds in self.odds_dict.items()}
        for team in team_fair_share_dict.keys():
            seed_str = str(self.team_seeds.get(team))
            if self.team_seeds.get(team) >= 13:
                team_fair_share_dict[team] += (0.03 / 16)
        
        for team in self.auction_results:
            fair_share_sum += team_fair_share_dict[team]
            seed_str = str(self.team_seeds.get(team))
        
        # Calculate new estimated pot
        team_implied_total = sale_price / team_fair_share_dict[team]
        estimated_total = total_sales / fair_share_sum
        
        
        last_team_sold = list(self.auction_results.keys())[-1]
        last_sale_price = self.auction_results[last_team_sold]


        print(f"\033[34m----------------------------------------------------------------------------------------------------------------------------\033[0m")
        print(f"{last_team_sold} ({seed_str}) sold for ${last_sale_price:,.2f}, and was expected to be {team_fair_share_dict[last_team_sold]*100:.2f}% of the pool")
        print(f"{last_team_sold} ({seed_str}) implies a total pot of {team_implied_total:,.2f}")
        print("")
        print(f"Total Auction sales: ${total_sales:,.2f}")
        print(f"Total Expected Pool % Sold: {fair_share_sum*100:,.2f}%")
        print(f"All Teams Implied Total Pot: ${estimated_total:,.2f}")
        
        # Blend new estimate with previous estimate (50% weight)
        # FIX FIX FIX, DECAYING WEIGHTING, TEST ON PAST YEARS
        initial_estimate = 200000
        self.estimated_pot = (initial_estimate + estimated_total) / 2

        print("")
        print(f"Previous estimated pot: ${self.last_pot:,.2f}")
        print(f"\033[32mUpdated estimated pot: ${self.estimated_pot:,.2f}\033[0m .... 50% initial estimate: ${round(initial_estimate):,.2f}, 50% total_expected_pot: ${round(estimated_total):,.2f}")
        print(f"\033[34m----------------------------------------------------------------------------------------------------------------------------\033[0m")
        print("")
    
    def run_live_update(self):
        while True:
            team = input("Enter team name (or 'exit' to stop, 'undo' to revert last entry): ").strip()
            if team.lower() == 'exit':
                break
            if team.lower() == 'undo' and self.auction_results:
                last_team = list(self.auction_results.keys())[-1]
                self.estimated_pot = self.last_pot
                del self.auction_results[last_team]
                print(f"Undo last entry: {last_team}")
                continue
            if team not in self.odds_dict:
                print("Invalid team. Try again.")
                continue
            if team in self.auction_results:
                print("Error: Team has already been sold.")
                continue
            try:
                price = float(input(f"Enter sale price for {team}: ").strip())
                self.update_pot(team, price)
                fair_values = self.calculate_fair_value()
                for team, value in fair_values.items():
                    seed = self.team_seeds[team.split(" (")[0]]
                    seed_str = str(seed)
                    if team in self.auction_results:
                        sale_price = self.auction_results[team]
                        if sale_price > value:
                            formatted_sale_price = f"\033[91m Sold for: ${sale_price:,.0f}\033[0m"
                        else:
                            formatted_sale_price = f"\033[32m Sold for: ${sale_price:,.0f}\033[0m"
                        formatted_team = f"\033[94m{team} ({seed_str})\033[0m"  
                        formatted_value = f"\033[94m{float(value):,.2f}\033[0m" 

                        print(f"{formatted_team}: {formatted_value}, {formatted_sale_price}")
                    else:
                        formatted_value = f"{float(value):,.2f}"
                        print(f"{team} ({seed_str}): {formatted_value}")

            except ValueError as e:
                print(f"Error: {e}")
        
    def past_auction_study(self, auction_results, year):
        team_implied_total_pot = {}
        all_teams_implied_total_pot = {}
        teams_in_auction_order = list(auction_results.keys())

        running_total = 0
        running_fair_pct = 0

        payout_percentages = [0.0075, 0.015, 0.0225, 0.035, 0.06, 0.08]
        team_fair_share_dict = {}

        for team, odds in auction.odds_dict.items():
            team_fair_share = .97 * sum(prob * pct for prob, pct in zip(odds, payout_percentages))

            seed = auction.team_seeds.get(team)
            if seed is None:
                print(f"Team not found in team_seeds: '{team}'")
            elif seed >= 13:
                team_fair_share += (0.03 / 16)
            team_fair_share_dict[team] = team_fair_share

        for team in teams_in_auction_order:
            price_paid = auction_results[team]
            running_total += price_paid
            
            if team in team_fair_share_dict:
                running_fair_pct += team_fair_share_dict[team]
            else:
                print(f"Warning: {team} not found in odds dictionary")
                continue
            
            if running_fair_pct > 0:
                all_teams_implication = running_total / running_fair_pct
                all_teams_implied_total_pot[team] = all_teams_implication

                individual_team_implication = price_paid / team_fair_share_dict[team]
                team_implied_total_pot[team] = individual_team_implication

        results_df = pd.DataFrame({
            'Auction_Order': list(range(1, len(team_implied_total_pot) + 1)),
            'Team': list(team_implied_total_pot.keys()),
            'Seed': [auction.team_seeds.get(team, 0) for team in team_implied_total_pot.keys()],
            'Price_Paid': [round(auction_results[team]) for team in team_implied_total_pot.keys()],
            'Team_Implied_Total_Pot': [round(value) for value in team_implied_total_pot.values()],
            'All_Teams_Implied_Total_Pot': [round(value) for value in all_teams_implied_total_pot.values()],
            'Cumulative_Spent': [round(sum(list(auction_results.values())[:i+1])) for i in range(len(team_implied_total_pot))],
            'Fair_Value_Pct': [round(team_fair_share_dict.get(team, 0)*100, 2) for team in team_implied_total_pot.keys()],
            'Cumulative_Fair_Pct': [round(sum([team_fair_share_dict.get(teams_in_auction_order[j], 0) for j in range(i+1)])*100, 2)
                                    for i in range(len(team_implied_total_pot))]
        })


        results_df.to_csv(f'implied_total_pot_{year}_auction.csv', index=False)
        return results_df

# Seed and Odds Data Below 2021 - 2024

team_seeds_2024 = {
    "Connecticut": 1,
    "Purdue": 1,
    "Houston": 1,
    "UNC": 1,
    "Arizona": 2,
    "Tennessee": 2,
    "Iowa State": 2,
    "Marquette": 2,
    "Creighton": 3,
    "Baylor": 3,
    "Kentucky": 3,
    "Illinois": 3,
    "Auburn": 4,
    "Alabama": 4,
    "Duke": 4,
    "Kansas": 4,
    "Gonzaga": 5,
    "Wisconsin": 5,
    "San Diego State": 5,
    "Saint Mary's": 5,
    "Texas Tech": 6,
    "BYU": 6,
    "South Carolina": 6,
    "Clemson": 6,
    "Florida": 7,
    "Texas": 7,
    "Washington State": 7,
    "Dayton": 7,
    "Nebraska": 8,
    "Mississippi State": 8,
    "Florida Atlantic": 8,
    "Utah State": 8,
    "Texas A&M": 9,
    "Northwestern": 9,
    "TCU": 9,
    "Michigan State": 9,
    "Drake": 10,
    "Nevada": 10,
    "Boise State/Colorado": 10,
    "Virginia/Colorado State": 10,
    "NC State": 11,
    "New Mexico": 11,
    "Oregon": 11,
    "Duquesne": 11,
    "UAB": 12,
    "McNeese State": 12,
    "Grand Canyon": 12,
    "James Madison": 12,
    "Yale": 13,
    "College of Charleston": 13,
    "Vermont": 13,
    "Samford": 13,
    "Morehead State": 14,
    "Oakland": 14,
    "Akron": 14,
    "Colgate": 14,
    "South Dakota State": 15,
    "Longwood": 16,
    "Stetson": 16,
    "Western Kentucky": 15,
    "Long Beach State": 15,
    "Howard/Wagner": 16,
    "Montana State/Grambling": 16,
    "Saint Peter's": 15,
    }
team_seeds_2023 = {
    "Houston": 1,
    "Alabama": 1,
    "UCLA": 2,
    "Purdue": 1,
    "Texas": 2,
    "Tennessee": 4,
    "Connecticut": 4,
    "Gonzaga": 3,
    "Arizona": 2,
    "Kansas": 1,
    "Marquette": 2,
    "Saint Mary's": 5,
    "Creighton": 6,
    "San Diego State": 5,
    "Baylor": 3,
    "Xavier": 3,
    "Kansas State": 3,
    "Utah State": 10,
    "Iowa State": 6,
    "Duke": 5,
    "Kentucky": 6,
    "West Virginia": 9,
    "Texas A&M": 7,
    "Indiana": 4,
    "Memphis": 8,
    "Maryland": 8,
    "Arkansas": 8,
    "Virginia": 4,
    "Florida Atlantic": 9,
    "Michigan State": 7,
    "Auburn": 9,
    "TCU": 6,
    "Boise State": 10,
    "USC": 10,
    "Miami FL": 5,
    "Providence": 11,
    "Iowa": 8,
    "Illinois": 9,
    "Penn State": 10,
    "Northwestern": 7,
    "Missouri": 7,
    "NC State": 11,
    "Drake": 12,
    "Mississippi St.": 11,
    "Oral Roberts": 12,
    "Nevada/Arizona State": 11,
    "Kent State": 13,
    "VCU": 12,
    "Charleston": 12,
    "Iona": 13,
    "Pittsburgh": 11,
    "Furman": 13,
    "Louisiana": 13,
    "UC Santa Barbara": 14,
    "Montana State": 14,
    "Vermont": 15,
    "Grand Canyon": 14,
    "Princeton": 15,
    "Colgate": 15,
    "Kennesaw State": 14,
    "Northern Kentucky": 16,
    "UNC Asheville": 15,
    "Texas A&M Corpus Chris": 16,
    "Howard": 16,
    "Southern": 16,
    "Southeast Missouri St.": 16,
    "FDU/Texas Southern": 16
    }
team_seeds_2022 = {
    "Gonzaga": 1,
    "Arizona": 1,
    "Kansas": 1,
    "Baylor": 1,
    "Kentucky": 2,
    "Auburn": 2,
    "Tennessee": 3,
    "Houston": 5,
    "Texas Tech": 3,
    "UCLA": 4,
    "Villanova": 2,
    "Iowa": 5,
    "Duke": 2,
    "Purdue": 3,
    "LSU": 6,
    "Texas": 6,
    "Saint Mary's": 5,
    "Connecticut": 5,
    "Illinois": 4,
    "Arkansas": 4,
    "San Diego State": 8,
    "Loyola Chicago": 10,
    "San Francisco": 10,
    "Wisconsin": 3,
    "Virginia Tech": 11,
    "Alabama": 6,
    "Colorado State": 6,
    "Ohio State": 7,
    "Murray State": 7,
    "Boise State": 8,
    "Michigan": 11,
    "USC": 7,
    "North Carolina": 8,
    "Iowa State": 11,
    "Providence": 4,
    "Memphis": 9,
    "Davidson": 10,
    "TCU": 9,
    "Michigan State": 7,
    "Seton Hall": 8,
    "Creighton": 9,
    "Miami FL": 10,
    "UAB": 12,
    "Marquette": 9,
    "Vermont": 13,
    "Indiana": 12,
    "South Dakota State": 13,
    "Chattanooga": 13,
    "Wyoming": 12,
    "Richmond": 12,
    "New Mexico State": 12,
    "Rutgers/ND": 11,
    "Colgate": 14,
    "Jacksonville State": 15,
    "Montana State": 14,
    "Akron": 13,
    "Saint Peter's": 15,
    "Longwood": 14,
    "Delaware": 15,
    "Cal State Fullerton": 15,
    "Yale": 14,
    "Georgia State": 16,
    "Norfolk State": 16,
    "Texas Southern": 16,
    "Wright State": 16,
    "Bryant": 16,
    "Texas A&M Corpus Chris": 16
    }
team_seeds_2021 = {
    "Gonzaga": 1,
    "Illinois": 1,
    "Michigan": 1,
    "Baylor": 1,
    "Houston": 2,
    "Iowa": 2,
    "Ohio State": 2,
    "Alabama": 2,
    "Villanova": 5,
    "Loyola Chicago": 8,
    "Purdue": 4,
    "Florida State": 4,
    "Virginia": 4,
    "Arkansas": 3,
    "Tennessee": 5,
    "USC": 6,
    "Wisconsin": 9,
    "Colorado": 5,
    "San Diego State": 6,
    "Texas Tech": 6,
    "Connecticut": 7,
    "West Virginia": 3,
    "Kansas": 3,
    "BYU": 6,
    "Texas": 3,
    "Creighton": 5,
    "St. Bonaventure": 9,
    "Oklahoma State": 4,
    "North Carolina": 8,
    "Maryland": 10,
    "LSU": 8,
    "Rutgers": 10,
    "Florida": 7,
    "Georgia Tech": 9,
    "Oregon": 7,
    "Utah State": 11,
    "Clemson": 7,
    "Syracuse": 11,
    "Virginia Tech": 10,
    "Oklahoma": 8,
    "VCU": 10,
    "Michigan State/UCLA": 11,
    "Missouri": 9,
    "Georgetown": 12,
    "Wichita State/Drake": 11,
    "North Texas": 13,
    "UC Santa Barbara": 12,
    "Oregon State": 12,
    "Ohio": 13,
    "Abilene Christian": 14,
    "Colgate": 14,
    "Liberty": 13,
    "UNC Greensboro": 13,
    "Winthrop": 12,
    "Eastern Washington": 14,
    "Grand Canyon": 15,
    "Morehead State": 14,
    "Cleveland State": 15,
    "Oral Roberts": 15,
    "Drexel": 16,
    "Iona": 15,
    "Hartford": 16,
    "Mount St. Mary's/Texas Southern": 16,
    "Norfolk State/Appalachian State": 16
    }

champ_odds_2024 = {
    "Connecticut": 23.4,
    "Purdue": 13.2,
    "Arizona": 10.5,
    "Houston": 9.8,
    "Tennessee": 7.7,
    "Auburn": 7.3,
    "UNC": 4.4,
    "Iowa State": 4.1,
    "Duke": 3.8,
    "Creighton": 2.5,
    "Illinois": 2.0,
    "Alabama": 1.4,
    "Kentucky": 1.2,
    "Gonzaga": 1.2,
    "Marquette": 0.8,
    "Florida": 0.6,
    "Baylor": 0.7,
    "Michigan State": 0.6,
    "Kansas": 0.5,
    "Wisconsin": 0.7,
    "BYU": 0.5,
    "New Mexico": 0.3,
    "Texas": 0.3,
    "Texas Tech": 0.3,
    "Nebraska": 0.2,
    "TCU": 0.2,
    "Mississippi State": 0.2,
    "Washington State": 0.2,
    "Clemson": 0.2,
    "Florida Atlantic": 0.2,
    "James Madison": 0.2,
    "San Diego State": 0.2,
    "Northwestern": 0.1,
    "Saint Mary's": 0.2,
    "Texas A&M": 0.1,
    "Dayton": 0.1,
    "Drake": 0.1,
    "South Carolina": 0.1,
    "Virginia/Colorado State": 0.1,
    "Vermont": 0.0,
    "Boise State/Colorado": 0.1,
    "NC State": 0.0,
    "Nevada": 0.0,
    "McNeese State": 0.0,
    "Oregon": 0.0,
    "Grand Canyon": 0.0,
    "Utah State": 0.0,
    "Yale": 0.0,
    "College of Charleston": 0.0,
    "Western Kentucky": 0.0,
    "UAB": 0.0,
    "Akron": 0.0,
    "Duquesne": 0.0,
    "Samford": 0.0,
    "Colgate": 0.0,
    "Morehead State": 0.0,
    "Oakland": 0.0,
    "Longwood": 0.0,
    "South Dakota State": 0.0,
    "Stetson": 0.0,
    "Long Beach State": 0.0,
    "Howard/Wagner": 0,
    "Montana State/Grambling": 0,
    "Saint Peter's": 0.0,
    }
second_place_odds_2024 = {
    "Connecticut": 33.2,
    "Purdue": 25.4,
    "Arizona": 18.7,
    "Houston": 20.3,
    "Tennessee": 16.5,
    "Auburn": 12.4,
    "UNC": 9.8,
    "Iowa State": 8.9,
    "Duke": 8.9,
    "Creighton": 7.4,
    "Illinois": 4.4,
    "Alabama": 3.6,
    "Kentucky": 4.7,
    "Gonzaga": 3.5,
    "Marquette": 2.3,
    "Florida": 2.1,
    "Baylor": 2.0,
    "Michigan State": 1.2,
    "Kansas": 1.2,
    "Wisconsin": 1.7,
    "BYU": 1.3,
    "New Mexico": 1.0,
    "Texas": 0.9,
    "Texas Tech": 1.1,
    "Nebraska": 0.7,
    "TCU": 0.5,
    "Mississippi State": 0.6,
    "Washington State": 0.5,
    "Clemson": 0.4,
    "Florida Atlantic": 0.4,
    "James Madison": 0.4,
    "San Diego State": 0.5,
    "Northwestern": 0.2,
    "Saint Mary's": 0.6,
    "Texas A&M": 0.6,
    "Dayton": 0.3,
    "Drake": 0.3,
    "South Carolina": 0.2,
    "Virginia/Colorado State": 0.1,
    "Vermont": 0.1,
    "Boise State/Colorado": 0.4,
    "NC State": 0.2,
    "Nevada": 0.2,
    "McNeese State": 0.1,
    "Oregon": 0.1,
    "Grand Canyon": 0.1,
    "Utah State": 0.1,
    "Yale": 0.1,
    "College of Charleston": 0.1,
    "Western Kentucky": 0.1,
    "UAB": 0.1,
    "Akron": 0.0,
    "Duquesne": 0.0,
    "Samford": 0.0,
    "Colgate": 0.0,
    "Morehead State": 0.0,
    "Oakland": 0.0,
    "Longwood": 0.0,
    "South Dakota State": 0.0,
    "Stetson": 0.0,
    "Long Beach State": 0.0,
    "Howard/Wagner": 0,
    "Montana State/Grambling": 0,
    "Saint Peter's": 0.0,
    }
final_four_odds_2024 = {
    "Connecticut": 43.1,
    "Purdue": 39.4,
    "Arizona": 40.8,
    "Houston": 35.4,
    "Tennessee": 27.4,
    "Auburn": 19.1,
    "UNC": 20.3,
    "Iowa State": 18.0,
    "Duke": 19.1,
    "Creighton": 14.4,
    "Illinois": 9.8,
    "Alabama": 12.2,
    "Kentucky": 13.0,
    "Gonzaga": 8.0,
    "Marquette": 7.7,
    "Florida": 6.8,
    "Baylor": 8.8,
    "Michigan State": 3.9,
    "Kansas": 2.4,
    "Wisconsin": 5.2,
    "BYU": 3.4,
    "New Mexico": 3.7,
    "Texas": 1.5,
    "Texas Tech": 3.8,
    "Nebraska": 2.0,
    "TCU": 1.8,
    "Mississippi State": 2.5,
    "Washington State": 1.7,
    "Clemson": 1.7,
    "Florida Atlantic": 1.2,
    "James Madison": 1.2,
    "San Diego State": 2.0,
    "Northwestern": 0.8,
    "Saint Mary's": 3.2,
    "Texas A&M": 1.0,
    "Dayton": 0.9,
    "Drake": 0.9,
    "South Carolina": 0.4,
    "Virginia/Colorado State": 0.5,
    "Vermont": 0.2,
    "Boise State/Colorado": 1.8,
    "NC State": 0.7,
    "Nevada": 0.7,
    "McNeese State": 0.3,
    "Oregon": 0.3,
    "Grand Canyon": 0.7,
    "Utah State": 0.1,
    "Yale": 0.1,
    "College of Charleston": 0.1,
    "Western Kentucky": 0.1,
    "UAB": 0.1,
    "Akron": 0.1,
    "Duquesne": 0.0,
    "Samford": 0.0,
    "Colgate": 0.0,
    "Morehead State": 0.0,
    "Oakland": 0.0,
    "Longwood": 0.0,
    "South Dakota State": 0.0,
    "Stetson": 0.0,
    "Long Beach State": 0.0,
    "Howard/Wagner": 0,
    "Montana State/Grambling": 0,
    "Saint Peter's": 0.0,
    }
elite_eight_odds_2024 = {
    "Connecticut": 57.7,
    "Purdue": 62.7,
    "Arizona": 59.5,
    "Houston": 48.4,
    "Tennessee": 50.0,
    "Auburn": 29.4,
    "UNC": 39.7,
    "Iowa State": 43.3,
    "Duke": 28.3,
    "Creighton": 32.9,
    "Illinois": 30.3,
    "Alabama": 29.9,
    "Kentucky": 32.8,
    "Gonzaga": 17.2,
    "Marquette": 24.6,
    "Florida": 17.3,
    "Baylor": 19.3,
    "Michigan State": 10.4,
    "Kansas": 12.4,
    "Wisconsin": 9.9,
    "BYU": 15.7,
    "New Mexico": 8.6,
    "Texas": 8.6,
    "Texas Tech": 14.2,
    "Nebraska": 4.9,
    "TCU": 5.6,
    "Mississippi State": 7.4,
    "Washington State": 5.9,
    "Clemson": 5.5,
    "Florida Atlantic": 3.7,
    "James Madison": 3.7,
    "San Diego State": 5.9,
    "Northwestern": 2.5,
    "Saint Mary's": 9.4,
    "Texas A&M": 4.2,
    "Dayton": 3.8,
    "Drake": 3.9,
    "South Carolina": 2.8,
    "Virginia/Colorado State": 2.0,
    "Vermont": 0.4,
    "Boise State/Colorado": 6.4,
    "NC State": 3.7,
    "Nevada": 3.2,
    "McNeese State": 1.3,
    "Oregon": 3.0,
    "Grand Canyon": 2.3,
    "Utah State": 0.5,
    "Yale": 0.4,
    "College of Charleston": 0.9,
    "Western Kentucky": 0.8,
    "UAB": 0.3,
    "Akron": 0.7,
    "Duquesne": 0.7,
    "Samford": 0.3,
    "Colgate": 0.2,
    "Morehead State": 0.2,
    "Oakland": 0.2,
    "Longwood": 0.1,
    "South Dakota State": 0.1,
    "Stetson": 0.1,
    "Long Beach State": 0,
    "Howard/Wagner": 0,
    "Montana State/Grambling": 0,
    "Saint Peter's": 0,   
    }
sweet_sixteen_odds_2024 = {
    "Connecticut": 81.3,
    "Purdue": 83.7,
    "Arizona": 79.9,
    "Houston": 74.5,
    "Tennessee": 74.7,
    "Auburn": 68.6,
    "UNC": 63.1,
    "Iowa State": 69.1,
    "Duke": 55.6,
    "Creighton": 68.4,
    "Illinois": 59.0,
    "Alabama": 61.6,
    "Kentucky": 56.1,
    "Gonzaga": 48.9,
    "Marquette": 48.4,
    "Florida": 32.6,
    "Baylor": 54.1,
    "Michigan State": 20.3,
    "Kansas": 40.2,
    "Wisconsin": 25.4,
    "BYU": 35.6,
    "New Mexico": 26.5,
    "Texas": 19,
    "Texas Tech": 29.8,
    "Nebraska": 13.3,
    "TCU": 13.2,
    "Mississippi State": 16.5,
    "Washington State": 15.7,
    "Clemson": 17.9,
    "Florida Atlantic": 11.2,
    "James Madison": 15.0,
    "San Diego State": 23.4,
    "Northwestern": 7.2,
    "Saint Mary's": 25.5,
    "Texas A&M": 11.6,
    "Dayton": 10.4,
    "Drake": 13.3,
    "South Carolina": 13.9,
    "Virginia/Colorado State": 6.3,
    "Vermont": 4.0,
    "Boise State/Colorado": 16.4,
    "NC State": 12.9,
    "Nevada": 9.4,
    "McNeese State": 7.7,
    "Oregon": 13.6,
    "Grand Canyon": 9.1,
    "Utah State": 2.9,
    "Yale": 4.9,
    "College of Charleston": 3.8,
    "Western Kentucky": 2.5,
    "UAB": 3.1,
    "Akron": 4.1,
    "Duquesne": 4.3,
    "Samford": 3.2,
    "Colgate": 1.5,
    "Morehead State": 1.2,
    "Oakland": 1.2,
    "Longwood": 0.7,
    "South Dakota State": 1.9,
    "Stetson": 0.3,
    "Long Beach State": 0.4,
    "Howard/Wagner": 0.1,
    "Montana State/Grambling": 0.1,
    "Saint Peter's": 0,
    }
round_32_odds_2024 = {
    "Connecticut": 97.7,
    "Purdue": 99.1,
    "Arizona": 96.8,
    "Houston": 96.5,
    "Tennessee": 98.7,
    "Auburn": 88.2,
    "UNC": 98.1,
    "Iowa State": 91.3,
    "Duke": 85.9,
    "Creighton": 88.5,
    "Illinois": 91.8,
    "Alabama": 87,
    "Kentucky": 92.2,
    "Gonzaga": 78.4,
    "Marquette": 87.5,
    "Florida": 61.9,
    "Baylor": 90.9,
    "Michigan State": 53.2,
    "Kansas": 81.5,
    "Wisconsin": 56.9,
    "BYU": 78.9,
    "New Mexico": 55.1,
    "Texas": 66.6,
    "Texas Tech": 62.4,
    "Nebraska": 50.5,
    "TCU": 69.5,
    "Mississippi State": 46.8,
    "Washington State": 53.8,
    "Clemson": 44.9,
    "Florida Atlantic": 57.6,
    "James Madison": 43.1,
    "San Diego State": 75.5,
    "Northwestern": 42.4,
    "Saint Mary's": 65.1,
    "Texas A&M": 49.5,
    "Dayton": 50.6,
    "Drake": 46.2,
    "South Carolina": 51.7,
    "Virginia/Colorado State": 33.4,
    "Vermont": 14.1,
    "Boise State/Colorado": 38,
    "NC State": 37.6,
    "Nevada": 49.4,
    "McNeese State": 21.6,
    "Oregon": 48.3,
    "Grand Canyon": 34.9,
    "Utah State": 30.5,
    "Yale": 11.8,
    "College of Charleston": 13.0,
    "Western Kentucky": 12.5,
    "UAB": 24.5,
    "Akron": 11.5,
    "Duquesne": 21.1,
    "Samford": 18.5,
    "Colgate": 9.1,
    "Morehead State": 8.2,
    "Oakland": 7.8,
    "Longwood": 3.5,
    "South Dakota State": 8.7,
    "Stetson": 2.3,
    "Long Beach State": 3.2,
    "Howard/Wagner": 1.9,
    "Montana State/Grambling": 0.9,
    "Saint Peter's": 1.3,
    }

champ_odds_2023 = {
    "Houston": 15.0,
    "Alabama": 13.5,
    "UCLA": 10.6,
    "Purdue": 6.3,
    "Texas": 6.0,
    "Tennessee": 5.7,
    "Connecticut": 5.1,
    "Gonzaga": 4.7,
    "Arizona": 4.1,
    "Kansas": 3.8,
    "Marquette": 3.3,
    "Saint Mary's": 1.8,
    "Creighton": 1.7,
    "San Diego State": 1.7,
    "Baylor": 1.6,
    "Xavier": 1.6,
    "Kansas State": 1.1,
    "Utah State": 0.9,
    "Iowa State": 0.9,
    "Duke": 0.8,
    "Kentucky": 0.8,
    "West Virginia": 0.7,
    "Texas A&M": 0.7,
    "Indiana": 0.7,
    "Memphis": 0.6,
    "Maryland": 0.6,
    "Arkansas": 0.5,
    "Virginia": 0.5,
    "Florida Atlantic": 0.5,
    "Michigan State": 0.5,
    "Auburn": 0.5,
    "TCU": 0.5,
    "Boise State": 0.3,
    "USC": 0.3,
    "Miami FL": 0.3,
    "Providence": 0.2,
    "Iowa": 0.2,
    "Illinois": 0.2,
    "Penn State": 0.2,
    "Northwestern": 0.1,
    "Missouri": 0.1,
    "NC State": 0.10,
    "Drake": 0.10,
    "Oral Roberts": 0.08,
    "Nevada/Arizona State": 0.09,
    "Kent State": 0.06,
    "VCU": 0.06,
    "Charleston": 0.04,
    "Iona": 0.03,
    "Pittsburgh": 0.11,
    "Furman": 0.01,
    "Louisiana": 0.007,
    "UC Santa Barbara": 0.005,
    "Montana State": 0.005,
    "Vermont": 0.004,
    "Grand Canyon": 0.002,
    "Princeton": 0.002,
    "Colgate": 0.001,
    "Kennesaw State": 0.001,
    "Northern Kentucky": 0.001,
    "UNC Asheville": 0.001,
    "Texas A&M Corpus Chris": 0.002,
    "Howard": 0.001,
    "Southern": 0.001,
    "FDU/Texas Southern": 0.001
    }
second_place_odds_2023 = {
    "Houston": 23.5,
    "Alabama": 23.4,
    "UCLA": 17.3,
    "Purdue": 12.7,
    "Texas": 11.0,
    "Tennessee": 11.3,
    "Connecticut": 9.0,
    "Gonzaga": 8.7,
    "Arizona": 9.0,
    "Kansas": 7.5,
    "Marquette": 7.7,
    "Saint Mary's": 3.8,
    "Creighton": 4.2,
    "San Diego State": 4.2,
    "Baylor": 4.1,
    "Xavier": 3.8,
    "Kansas State": 3.3,
    "Utah State": 2.5,
    "Iowa State": 2.1,
    "Duke": 2.2,
    "Kentucky": 2.2,
    "West Virginia": 1.8,
    "Texas A&M": 1.7,
    "Indiana": 1.8,
    "Memphis": 1.7,
    "Maryland": 1.5,
    "Arkansas": 1.4,
    "Virginia": 1.6,
    "Florida Atlantic": 1.5,
    "Michigan State": 1.5,
    "Auburn": 1.3,
    "TCU": 1.3,
    "Boise State": 0.9,
    "USC": 1.0,
    "Miami FL": 0.8,
    "Providence": 0.8,
    "Iowa": 0.7,
    "Illinois": 0.7,
    "Penn State": 0.6,
    "Northwestern": 0.4,
    "Missouri": 0.5,
    "NC State": 0.4,
    "Drake": 0.4,
    "Oral Roberts": 0.3,
    "Nevada/Arizona State": 0.28,
    "Kent State": 0.3,
    "VCU": 0.2,
    "Charleston": 0.2,
    "Iona": 0.1,
    "Pittsburgh": 0.38,
    "Furman": 0.08,
    "Louisiana": 0.05,
    "UC Santa Barbara": 0.04,
    "Montana State": 0.03,
    "Vermont": 0.03,
    "Grand Canyon": 0.01,
    "Princeton": 0.02,
    "Colgate": 0.01,
    "Kennesaw State": 0.008,
    "Northern Kentucky": 0.003,
    "UNC Asheville": 0.002,
    "Texas A&M Corpus Chris": 0.002,
    "Howard": 0.001,
    "Southern": 0.001,
    "FDU/Texas Southern": 0.001
    }
final_four_odds_2023 = {
    "Houston": 38.6,
    "Alabama": 35.8,
    "UCLA": 29.0,
    "Purdue": 23.5,
    "Texas": 21.3,
    "Tennessee": 20.7,
    "Connecticut": 16.4,
    "Gonzaga": 16.6,
    "Arizona": 16.7,
    "Kansas": 15.1,
    "Marquette": 16.1,
    "Saint Mary's": 7.9,
    "Creighton": 8.7,
    "San Diego State": 8.7,
    "Baylor": 8.8,
    "Xavier": 9.6,
    "Kansas State": 8.4,
    "Utah State": 5.6,
    "Iowa State": 5.6,
    "Duke": 5.4,
    "Kentucky": 5.9,
    "West Virginia": 4.1,
    "Texas A&M": 4.7,
    "Indiana": 5.2,
    "Memphis": 4.2,
    "Maryland": 3.5,
    "Arkansas": 3.5,
    "Virginia": 4.1,
    "Florida Atlantic": 3.8,
    "Michigan State": 4.3,
    "Auburn": 3.8,
    "TCU": 3.4,
    "Boise State": 2.6,
    "USC": 3.2,
    "Miami FL": 2.8,
    "Providence": 2.7,
    "Iowa": 2.2,
    "Illinois": 1.9,
    "Penn State": 2.1,
    "Northwestern": 1.3,
    "Missouri": 1.4,
    "NC State": 1.2,
    "Drake": 1.5,
    "Oral Roberts": 1.2,
    "Nevada/Arizona State": 1.1,
    "Kent State": 1.1,
    "VCU": 0.7,
    "Charleston": 0.6,
    "Iona": 0.4,
    "Pittsburgh": 1.4,
    "Furman": 0.3,
    "Louisiana": 0.2,
    "UC Santa Barbara": 0.2,
    "Montana State": 0.2,
    "Vermont": 0.2,
    "Grand Canyon": 0.09,
    "Princeton": 0.1,
    "Colgate": 0.1,
    "Kennesaw State": 0.06,
    "Northern Kentucky": 0.03,
    "UNC Asheville": 0.01,
    "Texas A&M Corpus Chris": 0.005,
    "Howard": 0.002,
    "Southern": 0.001,
    "FDU/Texas Southern": 0.01
    }
elite_eight_odds_2023 = {
    "Houston": 56.7,
    "Alabama": 52.2,
    "UCLA": 46.5,
    "Purdue": 36.7,
    "Texas": 39.8,
    "Tennessee": 32.1,
    "Connecticut": 31.0,
    "Gonzaga": 30.1,
    "Arizona": 34.0,
    "Kansas": 31.6,
    "Marquette": 33.1,
    "Saint Mary's": 17.5,
    "Creighton": 20.0,
    "San Diego State": 17.4,
    "Baylor": 20.9,
    "Xavier": 22.6,
    "Kansas State": 20.8,
    "Utah State": 14.1,
    "Iowa State": 14.0,
    "Duke": 10.8,
    "Kentucky": 14.9,
    "West Virginia": 8.7,
    "Texas A&M": 11.7,
    "Indiana": 12.2,
    "Memphis": 8.3,
    "Maryland": 7.7,
    "Arkansas": 9.4,
    "Virginia": 9.9,
    "Florida Atlantic": 7.7,
    "Michigan State": 11.5,
    "Auburn": 9.0,
    "TCU": 8.6,
    "Boise State": 6.7,
    "USC": 9.2,
    "Miami FL": 7.6,
    "Providence": 8.1,
    "Iowa": 5.9,
    "Illinois": 5.9,
    "Penn State": 6.1,
    "Northwestern": 4.1,
    "Missouri": 4.8,
    "NC State": 4.4,
    "Drake": 4.6,
    "Oral Roberts": 3.2,
    "Nevada/Arizona State": 3.4,
    "Kent State": 3.7,
    "VCU": 2.8,
    "Charleston": 2.7,
    "Iona": 1.9,
    "Pittsburgh": 4.7,
    "Furman": 1.4,
    "Louisiana": 1.0,
    "UC Santa Barbara": 1.1,
    "Montana State": 1.2,
    "Vermont": 1.1,
    "Grand Canyon": 0.5,
    "Princeton": 0.7,
    "Colgate": 0.6,
    "Kennesaw State": 0.5,
    "Northern Kentucky": 0.2,
    "UNC Asheville": 0.1,
    "Texas A&M Corpus Chris": 0.041,
    "Howard": 0.03,
    "Southern": 0.03,
    "FDU/Texas Southern": 0.01
    }
sweet_sixteen_odds_2023 = {
    "Houston": 71.6,
    "Alabama": 69.8,
    "UCLA": 71.1,
    "Purdue": 63.4,
    "Texas": 60.4,
    "Tennessee": 57.7,
    "Connecticut": 51.1,
    "Gonzaga": 60.3,
    "Arizona": 56.4,
    "Kansas": 60.8,
    "Marquette": 53.2,
    "Saint Mary's": 33.5,
    "Creighton": 39.1,
    "San Diego State": 45.2,
    "Baylor": 42.4,
    "Xavier": 49.3,
    "Kansas State": 42.9,
    "Utah State": 28.0,
    "Iowa State": 32.4,
    "Duke": 26.2,
    "Kentucky": 31.3,
    "West Virginia": 15.7,
    "Texas A&M": 22.9,
    "Indiana": 37.1,
    "Memphis": 18.9,
    "Maryland": 14.2,
    "Arkansas": 22.8,
    "Virginia": 32.1,
    "Florida Atlantic": 17.7,
    "Michigan State": 23.0,
    "Auburn": 15.9,
    "TCU": 24.1,
    "Boise State": 16.4,
    "USC": 19.4,
    "Miami FL": 27.3,
    "Providence": 20.2,
    "Iowa": 11.4,
    "Illinois": 16.0,
    "Penn State": 14.1,
    "Northwestern": 11.4,
    "Missouri": 12.5,
    "NC State": 13.2,
    "Drake": 19.1,
    "Oral Roberts": 11.2,
    "Nevada/Arizona State": 12.2,
    "Kent State": 16.5,
    "VCU": 8.8,
    "Charleston": 13.4,
    "Iona": 6.6,
    "Pittsburgh": 15,
    "Furman": 9.3,
    "Louisiana": 4.9,
    "UC Santa Barbara": 5.3,
    "Montana State": 5.6,
    "Vermont": 4.3,
    "Grand Canyon": 3.5,
    "Princeton": 3.1,
    "Colgate": 2.7,
    "Kennesaw State": 3.4,
    "Northern Kentucky": 1.1,
    "UNC Asheville": 1.0,
    "Texas A&M Corpus Chris": 0.31,
    "Howard": 0.4,
    "Southern": 0.04,
    "FDU/Texas Southern": 0.01
    }
round_32_odds_2023 = {
    "Houston": 93.8,
    "Alabama": 97.6,
    "UCLA": 94.6,
    "Purdue": 98.3,
    "Texas": 88.8,
    "Tennessee": 84.1,
    "Connecticut": 80.1,
    "Gonzaga": 87.0,
    "Arizona": 87.0,
    "Kansas": 95.4,
    "Marquette": 83.7,
    "Saint Mary's": 69.3,
    "Creighton": 67.7,
    "San Diego State": 70.4,
    "Baylor": 78.3,
    "Xavier": 85.0,
    "Kansas State": 78.4,
    "Utah State": 62.4,
    "Iowa State": 62.3,
    "Duke": 62.7,
    "Kentucky": 57.3,
    "West Virginia": 51.8,
    "Texas A&M": 57.6,
    "Indiana": 63.4,
    "Memphis": 51.2,
    "Maryland": 48.2,
    "Arkansas": 55.5,
    "Virginia": 67.7,
    "Florida Atlantic": 48.8,
    "Michigan State": 52.6,
    "Auburn": 54.7,
    "TCU": 60.8,
    "Boise State": 55.4,
    "USC": 47.4,
    "Miami FL": 55.9,
    "Providence": 42.7,
    "Iowa": 45.3,
    "Illinois": 44.5,
    "Penn State": 42.4,
    "Northwestern": 44.6,
    "Missouri": 37.6,
    "NC State": 32.3,
    "Drake": 44.1,
    "Oral Roberts": 37.3,
    "Nevada/Arizona State": 39.2,
    "Kent State": 36.6,
    "VCU": 30.7,
    "Charleston": 29.6,
    "Iona": 19.9,
    "Pittsburgh": 37.7,
    "Furman": 32.3,
    "Louisiana": 15.9,
    "UC Santa Barbara": 21.7,
    "Montana State": 21.6,
    "Vermont": 16.3,
    "Grand Canyon": 13.0,
    "Princeton": 13.0,
    "Colgate": 11.2,
    "Kennesaw State": 15.0,
    "Northern Kentucky": 6.2,
    "UNC Asheville": 5.4,
    "Texas A&M Corpus Chris": 2.5,
    "Howard": 4.6,
    "Southern": 1.1,
    "FDU/Texas Southern": 0.6
    }

champ_odds_538_2023 = {}
second_place_odds_538_2023 = {}
final_four_odds_538_2023 = {}
elite_eight_odds_538_2023 = {}
sweet_sixteen_odds_538_2023 = {}
round_32_odds_538_2023 = {}

champ_odds_2022 = {
    "Gonzaga": 27.5,
    "Arizona": 8.9,
    "Kansas": 6.6,
    "Baylor": 6.4,
    "Kentucky": 6.2,
    "Auburn": 5.6,
    "Tennessee": 5.1,
    "Houston": 5.0,
    "Texas Tech": 4.0,
    "UCLA": 3.8,
    "Villanova": 3.6,
    "Iowa": 3.5,
    "Duke": 3.3,
    "Purdue": 1.9,
    "LSU": 0.9,
    "Texas": 0.7,
    "Saint Mary's": 0.7,
    "Connecticut": 0.7,
    "Illinois": 0.7,
    "Arkansas": 0.5,
    "San Diego State": 0.5,
    "Loyola Chicago": 0.4,
    "San Francisco": 0.3,
    "Wisconsin": 0.3,
    "Virginia Tech": 0.3,
    "Alabama": 0.3,
    "Colorado State": 0.2,
    "Ohio State": 0.2,
    "Murray State": 0.2,
    "Boise State": 0.2,
    "Michigan": 0.2,
    "USC": 0.2,
    "North Carolina": 0.1,
    "Iowa State": 0.1,
    "Providence": 0.1,
    "Memphis": 0.1,
    "Davidson": 0.1,
    "TCU": 0.1,
    "Michigan State": 0.1,
    "Seton Hall": 0.09,
    "Creighton": 0.06,
    "Miami FL": 0.06,
    "UAB": 0.06,
    "Marquette": 0.05,
    "Vermont": 0.05,
    "Indiana": 0.05,
    "Rutgers/ND": 0.048,
    "South Dakota State": 0.03,
    "Chattanooga": 0.02,
    "Wyoming": 0.02,
    "Richmond": 0.01,
    "New Mexico State": 0.01,
    "Colgate": 0.001,
    "Jacksonville State": 0.001,
    "Montana State": 0.001,
    "Akron": 0.001,
    "Saint Peter's": 0.001,
    "Longwood": 0.001,
    "Delaware": 0.001,
    "Cal State Fullerton": 0.001,
    "Yale": 0.001,
    "Georgia State": 0.001,
    "Norfolk State": 0.001,
    "Texas Southern": 0.001,
    "Wright State": 0.001,
    "Bryant": 0.001,
    "Texas A&M Corpus Chris": 0.001
    }
second_place_odds_2022 = {
    "Gonzaga": 38.5,
    "Arizona": 18.1,
    "Kansas": 14.6,
    "Baylor": 11.6,
    "Kentucky": 11.0,
    "Auburn": 13.2,
    "Tennessee": 11.4,
    "Houston": 10.5,
    "Texas Tech": 7.9,
    "UCLA": 7.4,
    "Villanova": 8.5,
    "Iowa": 8.7,
    "Duke": 6.7,
    "Purdue": 4.2,
    "LSU": 2.8,
    "Texas": 1.8,
    "Saint Mary's": 1.7,
    "Connecticut": 1.7,
    "Illinois": 2.1,
    "Arkansas": 1.4,
    "San Diego State": 1.6,
    "Loyola Chicago": 1.2,
    "San Francisco": 0.9,
    "Wisconsin": 1.3,
    "Virginia Tech": 0.8,
    "Alabama": 0.8,
    "Colorado State": 0.7,
    "Ohio State": 0.7,
    "Murray State": 0.5,
    "Boise State": 0.5,
    "Michigan": 0.6,
    "USC": 0.7,
    "North Carolina": 0.5,
    "Iowa State": 0.6,
    "Providence": 0.6,
    "Memphis": 0.4,
    "Davidson": 0.4,
    "TCU": 0.4,
    "Michigan State": 0.4,
    "Seton Hall": 0.4,
    "Creighton": 0.3,
    "Miami FL": 0.3,
    "UAB": 0.3,
    "Marquette": 0.2,
    "Vermont": 0.2,
    "Indiana": 0.2,
    "Rutgers/ND": 0.14,
    "South Dakota State": 0.2,
    "Chattanooga": 0.1,
    "Wyoming": 0.08,
    "Richmond": 0.10,
    "New Mexico State": 0.06,
    "Colgate": 0.01,
    "Jacksonville State": 0.006,
    "Montana State": 0.005,
    "Akron": 0.004,
    "Saint Peter's": 0.004,
    "Longwood": 0.004,
    "Delaware": 0.002,
    "Cal State Fullerton": 0.002,
    "Yale": 0.001,
    "Georgia State": 0.001,
    "Norfolk State": 0.001,
    "Texas Southern": 0.001,
    "Wright State": 0.001,
    "Bryant": 0.001,
    "Texas A&M Corpus Chris": 0.001
    }
final_four_odds_2022 = {
    "Gonzaga": 53.7,
    "Arizona": 29.1,
    "Kansas": 27.9,
    "Baylor": 25.2,
    "Kentucky": 23.6,
    "Auburn": 26.3,
    "Tennessee": 20.0,
    "Houston": 17.6,
    "Texas Tech": 15.4,
    "UCLA": 17.2,
    "Villanova": 15.7,
    "Iowa": 18.3,
    "Duke": 13.6,
    "Purdue": 11.4,
    "LSU": 7.6,
    "Texas": 5.2,
    "Saint Mary's": 5.1,
    "Connecticut": 4.4,
    "Illinois": 4.7,
    "Arkansas": 3.6,
    "San Diego State": 4.6,
    "Loyola Chicago": 3.1,
    "San Francisco": 3.2,
    "Wisconsin": 4.5,
    "Virginia Tech": 2.8,
    "Alabama": 2.4,
    "Colorado State": 2.0,
    "Ohio State": 1.9,
    "Murray State": 1.9,
    "Boise State": 1.5,
    "Michigan": 1.8,
    "USC": 2.5,
    "North Carolina": 2.0,
    "Iowa State": 2.1,
    "Providence": 2.1,
    "Memphis": 1.2,
    "Davidson": 1.3,
    "TCU": 1.3,
    "Michigan State": 1.3,
    "Seton Hall": 1.3,
    "Creighton": 1.2,
    "Miami FL": 1.4,
    "UAB": 0.8,
    "Marquette": 1.1,
    "Vermont": 0.7,
    "Indiana": 0.7,
    "South Dakota State": 0.9,
    "Chattanooga": 0.5,
    "Wyoming": 0.4,
    "Richmond": 0.5,
    "New Mexico State": 0.3,
    "Rutgers/ND": 0.7,
    "Colgate": 0.1,
    "Jacksonville State": 0.06,
    "Montana State": 0.03,
    "Akron": 0.05,
    "Saint Peter's": 0.04,
    "Longwood": 0.03,
    "Delaware": 0.03,
    "Cal State Fullerton": 0.02,
    "Yale": 0.02,
    "Georgia State": 0.009,
    "Norfolk State": 0.009,
    "Texas Southern": 0.006,
    "Wright State": 0.002,
    "Bryant": 0.002,
    "Texas A&M Corpus Chris": 0.001
    }
elite_eight_odds_2022 = {
    "Gonzaga": 70.8,
    "Arizona": 47.2,
    "Kansas": 44.3,
    "Baylor": 43.3,
    "Kentucky": 41.3,
    "Auburn": 47.9,
    "Tennessee": 39.2,
    "Houston": 29.8,
    "Texas Tech": 38.2,
    "UCLA": 31.4,
    "Villanova": 32.3,
    "Iowa": 31.4,
    "Duke": 35.5,
    "Purdue": 24.1,
    "LSU": 18.2,
    "Texas": 12.2,
    "Saint Mary's": 11.7,
    "Connecticut": 9.9,
    "Illinois": 10.8,
    "Arkansas": 8.5,
    "San Diego State": 10.1,
    "Loyola Chicago": 9.0,
    "San Francisco": 8.6,
    "Wisconsin": 13.1,
    "Virginia Tech": 7.6,
    "Alabama": 9.9,
    "Colorado State": 6.5,
    "Ohio State": 6.2,
    "Murray State": 5.7,
    "Boise State": 3.9,
    "Michigan": 6.2,
    "USC": 7.8,
    "North Carolina": 5.9,
    "Iowa State": 6.7,
    "Providence": 5.7,
    "Memphis": 3.3,
    "Davidson": 6.1,
    "TCU": 4.0,
    "Michigan State": 6.1,
    "Seton Hall": 3.9,
    "Creighton": 3.6,
    "Miami FL": 5.1,
    "UAB": 2.5,
    "Marquette": 3.6,
    "Vermont": 2.3,
    "Indiana": 2.2,
    "South Dakota State": 3.0,
    "Chattanooga": 1.7,
    "Wyoming": 1.3,
    "Richmond": 1.8,
    "New Mexico State": 1.2,
    "Rutgers/ND": 3.5,
    "Colgate": 0.9,
    "Jacksonville State": 0.4,
    "Montana State": 0.4,
    "Akron": 0.4,
    "Saint Peter's": 0.3,
    "Longwood": 0.3,
    "Delaware": 0.3,
    "Cal State Fullerton": 0.3,
    "Yale": 0.2,
    "Georgia State": 0.07,
    "Norfolk State": 0.1,
    "Texas Southern": 0.05,
    "Wright State": 0.02,
    "Bryant": 0.02,
    "Texas A&M Corpus Chris": 0.003
    }
sweet_sixteen_odds_2022 = {
    "Gonzaga": 84.4,
    "Arizona": 76.3,
    "Kansas": 68.7,
    "Baylor": 71.9,
    "Kentucky": 64.9,
    "Auburn": 68.8,
    "Tennessee": 65.4,
    "Houston": 54.4,
    "Texas Tech": 63.7,
    "UCLA": 58.2,
    "Villanova": 58.8,
    "Iowa": 60.4,
    "Duke": 63.6,
    "Purdue": 50.5,
    "LSU": 40.2,
    "Texas": 27.9,
    "Saint Mary's": 27.5,
    "Connecticut": 39.1,
    "Illinois": 28.2,
    "Arkansas": 36.0,
    "San Diego State": 21.2,
    "Loyola Chicago": 22.2,
    "San Francisco": 19.1,
    "Wisconsin": 34.8,
    "Virginia Tech": 19.9,
    "Alabama": 23.1,
    "Colorado State": 16.7,
    "Ohio State": 16.9,
    "Murray State": 14.1,
    "Boise State": 8.1,
    "Michigan": 16.0,
    "USC": 16.8,
    "North Carolina": 16.1,
    "Iowa State": 19.8,
    "Providence": 18.9,
    "Memphis": 7.1,
    "Davidson": 17.1,
    "TCU": 11.7,
    "Michigan State": 17.2,
    "Seton Hall": 11.5,
    "Creighton": 9.7,
    "Miami FL": 12.3,
    "UAB": 9.7,
    "Marquette": 11.1,
    "Vermont": 14.9,
    "Indiana": 7.0,
    "South Dakota State": 12.3,
    "Chattanooga": 7.7,
    "Wyoming": 4.8,
    "Richmond": 8.4,
    "New Mexico State": 9.9,
    "Rutgers/ND": 10.8,
    "Colgate": 5.3,
    "Jacksonville State": 2.1,
    "Montana State": 2.4,
    "Akron": 2.5,
    "Saint Peter's": 1.9,
    "Longwood": 1.8,
    "Delaware": 2.1,
    "Cal State Fullerton": 2.2,
    "Yale": 1.7,
    "Georgia State": 0.4,
    "Norfolk State": 0.9,
    "Texas Southern": 0.4,
    "Wright State": 0.3,
    "Bryant": 0.2,
    "Texas A&M Corpus Chris": 0.07
        }
round_32_odds_2022 = {
    "Gonzaga": 97.9,
    "Arizona": 97.1,
    "Kansas": 96.4,
    "Baylor": 94.5,
    "Kentucky": 91.1,
    "Auburn": 91.5,
    "Tennessee": 91.5,
    "Houston": 77.3,
    "Texas Tech": 89.7,
    "UCLA": 88.4,
    "Villanova": 89.4,
    "Iowa": 80.5,
    "Duke": 90.4,
    "Purdue": 89.0,
    "LSU": 62.4,
    "Texas": 55.5,
    "Saint Mary's": 63.0,
    "Connecticut": 70.6,
    "Illinois": 68.8,
    "Arkansas": 64.5,
    "San Diego State": 61.0,
    "Loyola Chicago": 54.3,
    "San Francisco": 54.8,
    "Wisconsin": 75.5,
    "Virginia Tech": 44.5,
    "Alabama": 62.3,
    "Colorado State": 50.4,
    "Ohio State": 45.7,
    "Murray State": 45.2,
    "Boise State": 50.6,
    "Michigan": 49.6,
    "USC": 54.5,
    "North Carolina": 55.3,
    "Iowa State": 37.6,
    "Providence": 55.9,
    "Memphis": 49.4,
    "Davidson": 49.8,
    "TCU": 49.9,
    "Michigan State": 50.2,
    "Seton Hall": 50.1,
    "Creighton": 39.0,
    "Miami FL": 45.5,
    "UAB": 22.7,
    "Marquette": 44.7,
    "Vermont": 35.5,
    "Indiana": 21.1,
    "South Dakota State": 44.1,
    "Chattanooga": 31.2,
    "Wyoming": 15.9,
    "Richmond": 19.5,
    "New Mexico State": 29.4,
    "Rutgers/ND": 37.7,
    "Colgate": 24.5,
    "Jacksonville State": 8.5,
    "Montana State": 10.3,
    "Akron": 11.6,
    "Saint Peter's": 8.9,
    "Longwood": 8.5,
    "Delaware": 10.6,
    "Cal State Fullerton": 9.6,
    "Yale": 11.0,
    "Georgia State": 2.1,
    "Norfolk State": 5.5,
    "Texas Southern": 2.8,
    "Wright State": 1.6,
    "Bryant": 1.3,
    "Texas A&M Corpus Chris": 0.8
    }

champ_odds_2021 = {
    "Gonzaga": 34.4,
    "Illinois": 10.7,
    "Michigan": 10.4,
    "Baylor": 8.2,
    "Houston": 7.4,
    "Iowa": 6.4,
    "Ohio State": 3.7,
    "Alabama": 2.7,
    "Villanova": 1.2,
    "Loyola Chicago": 1.1,
    "Purdue": 1.0,
    "Florida State": 0.9,
    "Virginia": 0.9,
    "Arkansas": 0.9,
    "Tennessee": 0.8,
    "USC": 0.8,
    "Wisconsin": 0.7,
    "Colorado": 0.7,
    "San Diego State": 0.7,
    "Texas Tech": 0.6,
    "Connecticut": 0.6,
    "West Virginia": 0.6,
    "Kansas": 0.6,
    "BYU": 0.6,
    "Texas": 0.6,
    "Creighton": 0.5,
    "St. Bonaventure": 0.3,
    "Oklahoma State": 0.3,
    "North Carolina": 0.2,
    "Maryland": 0.2,
    "LSU": 0.2,
    "Rutgers": 0.2,
    "Florida": 0.2,
    "Georgia Tech": 0.1,
    "Oregon": 0.1,
    "Utah State": 0.1,
    "Clemson": 0.10,
    "Syracuse": 0.08,
    "Virginia Tech": 0.07,
    "Oklahoma": 0.06,
    "VCU": 0.05,
    "Michigan State/UCLA": 0.05,
    "Missouri": 0.03,
    "Georgetown": 0.03,
    "Wichita State/Drake": 0.023,
    "North Texas": 0.01,
    "UC Santa Barbara": 0.010,
    "Oregon State": 0.008,
    "Ohio": 0.005,
    "Abilene Christian": 0.004,
    "Colgate": 0.004,
    "Liberty": 0.004,
    "UNC Greensboro": 0.001,
    "Winthrop": 0.001,
    "Eastern Washington": 0.001,
    "Grand Canyon": 0.001,
    "Morehead State": 0.001,
    "Cleveland State": 0.001,
    "Oral Roberts": 0.001,
    "Drexel": 0.001,
    "Iona": 0.001,
    "Hartford": 0.001,
    "Mount St. Mary's/Texas Southern": 0.002,
    "Norfolk State/Appalachian State": 0.002
    }
second_place_odds_2021 = {
    "Gonzaga": 46.3,
    "Illinois": 22.2,
    "Michigan": 17.4,
    "Baylor": 18.0,
    "Houston": 16.8,
    "Iowa": 11.3,
    "Ohio State": 10.1,
    "Alabama": 5.8,
    "Villanova": 4.0,
    "Loyola Chicago": 3.3,
    "Purdue": 3.3,
    "Florida State": 2.3,
    "Virginia": 2.1,
    "Arkansas": 3.2,
    "Tennessee": 2.8,
    "USC": 1.9,
    "Wisconsin": 2.4,
    "Colorado": 1.8,
    "San Diego State": 2.4,
    "Texas Tech": 2.3,
    "Connecticut": 1.6,
    "West Virginia": 2.5,
    "Kansas": 1.6,
    "BYU": 1.6,
    "Texas": 1.6,
    "Creighton": 1.3,
    "St. Bonaventure": 0.9,
    "Oklahoma State": 1.4,
    "North Carolina": 1.0,
    "Maryland": 0.6,
    "LSU": 0.6,
    "Rutgers": 0.9,
    "Florida": 0.8,
    "Georgia Tech": 0.6,
    "Oregon": 0.4,
    "Utah State": 0.5,
    "Clemson": 0.5,
    "Syracuse": 0.5,
    "Virginia Tech": 0.4,
    "Oklahoma": 0.2,
    "VCU": 0.2,
    "Michigan State/UCLA": 0.26,
    "Missouri": 0.1,
    "Georgetown": 0.1,
    "Wichita State/Drake": 0.10,
    "North Texas": 0.10,
    "UC Santa Barbara": 0.05,
    "Oregon State": 0.06,
    "Ohio": 0.03,
    "Abilene Christian": 0.02,
    "Colgate": 0.04,
    "Liberty": 0.04,
    "UNC Greensboro": 0.010,
    "Winthrop": 0.02,
    "Eastern Washington": 0.004,
    "Grand Canyon": 0.005,
    "Morehead State": 0.005,
    "Cleveland State": 0.001,
    "Oral Roberts": 0.001,
    "Drexel": 0.001,
    "Iona": 0.001,
    "Hartford": 0.001,
    "Mount St. Mary's/Texas Southern": 0.002,
    "Norfolk State/Appalachian State": 0.002
    }
final_four_odds_2021 = {
    "Gonzaga": 60.5,
    "Illinois": 34.5,
    "Michigan": 37.6,
    "Baylor": 31.5,
    "Houston": 28.2,
    "Iowa": 19.3,
    "Ohio State": 21.0,
    "Alabama": 17.8,
    "Villanova": 9.5,
    "Loyola Chicago": 6.9,
    "Purdue": 8.0,
    "Florida State": 8.4,
    "Virginia": 4.7,
    "Arkansas": 8.5,
    "Tennessee": 6.7,
    "USC": 4.5,
    "Wisconsin": 5.6,
    "Colorado": 6.6,
    "San Diego State": 5.8,
    "Texas Tech": 6.2,
    "Connecticut": 5.8,
    "West Virginia": 6.3,
    "Kansas": 4.1,
    "BYU": 6.1,
    "Texas": 6.5,
    "Creighton": 3.1,
    "St. Bonaventure": 3.7,
    "Oklahoma State": 4.0,
    "North Carolina": 2.7,
    "Maryland": 2.6,
    "LSU": 2.5,
    "Rutgers": 2.5,
    "Florida": 2.8,
    "Georgia Tech": 1.8,
    "Oregon": 1.3,
    "Utah State": 1.9,
    "Clemson": 1.5,
    "Syracuse": 1.5,
    "Virginia Tech": 1.5,
    "Oklahoma": 0.7,
    "VCU": 0.7,
    "Michigan State/UCLA": 1.3,
    "Missouri": 0.4,
    "Georgetown": 0.7,
    "Wichita State/Drake": 0.38,
    "North Texas": 0.5,
    "UC Santa Barbara": 0.2,
    "Oregon State": 0.3,
    "Ohio": 0.1,
    "Abilene Christian": 0.2,
    "Colgate": 0.3,
    "Liberty": 0.2,
    "UNC Greensboro": 0.1,
    "Winthrop": 0.1,
    "Eastern Washington": 0.03,
    "Grand Canyon": 0.04,
    "Morehead State": 0.04,
    "Cleveland State": 0.01,
    "Oral Roberts": 0.009,
    "Drexel": 0.009,
    "Iona": 0.003,
    "Hartford": 0.001,
    "Mount St. Mary's/Texas Southern": 0.002,
    "Norfolk State/Appalachian State": 0.002
    }
elite_eight_odds_2021 = {
    "Gonzaga": 77.3,
    "Illinois": 52.7,
    "Michigan": 53.3,
    "Baylor": 46.6,
    "Houston": 49.9,
    "Iowa": 49.7,
    "Ohio State": 41.9,
    "Alabama": 37.9,
    "Villanova": 18.4,
    "Loyola Chicago": 13.9,
    "Purdue": 15.7,
    "Florida State": 16.8,
    "Virginia": 10.3,
    "Arkansas": 21.0,
    "Tennessee": 15.4,
    "USC": 17.5,
    "Wisconsin": 10.8,
    "Colorado": 13.4,
    "San Diego State": 14.7,
    "Texas Tech": 15.4,
    "Connecticut": 14.3,
    "West Virginia": 17.0,
    "Kansas": 17.5,
    "BYU": 16.2,
    "Texas": 17.5,
    "Creighton": 7.3,
    "St. Bonaventure": 7.8,
    "Oklahoma State": 10.6,
    "North Carolina": 6.0,
    "Maryland": 7.7,
    "LSU": 5.7,
    "Rutgers": 7.6,
    "Florida": 8.6,
    "Georgia Tech": 4.8,
    "Oregon": 6.9,
    "Utah State": 6.2,
    "Clemson": 5.2,
    "Syracuse": 5.2,
    "Virginia Tech": 5.3,
    "Oklahoma": 2.2,
    "VCU": 4.5,
    "Michigan State/UCLA": 4.8,
    "Missouri": 1.4,
    "Georgetown": 2.4,
    "Wichita State/Drake": 2.9,
    "North Texas": 1.8,
    "UC Santa Barbara": 0.9,
    "Oregon State": 1.4,
    "Ohio": 0.6,
    "Abilene Christian": 1.5,
    "Colgate": 1.4,
    "Liberty": 1.0,
    "UNC Greensboro": 0.6,
    "Winthrop": 0.6,
    "Eastern Washington": 0.5,
    "Grand Canyon": 0.6,
    "Morehead State": 0.4,
    "Cleveland State": 0.1,
    "Oral Roberts": 0.1,
    "Drexel": 0.09,
    "Iona": 0.05,
    "Hartford": 0.02,
    "Mount St. Mary's/Texas Southern": 0.008,
    "Norfolk State/Appalachian State": 0.003
    }
sweet_sixteen_odds_2021 = {
   "Gonzaga": 91.2,
   "Illinois": 67.8,
   "Michigan": 72.7,
   "Baylor": 67.2,
   "Houston": 70.6,
   "Iowa": 70.6,
   "Ohio State": 66.2,
   "Alabama": 58.6,
   "Villanova": 45.8,
   "Loyola Chicago": 22.3,
   "Purdue": 40.1,
   "Florida State": 46.9,
   "Virginia": 43.3,
   "Arkansas": 43.8,
   "Tennessee": 45.3,
   "USC": 41.0,
   "Wisconsin": 20.1,
   "Colorado": 37.2,
   "San Diego State": 35.7,
   "Texas Tech": 32.8,
   "Connecticut": 25.3,
   "West Virginia": 44.1,
   "Kansas": 43.9,
   "BYU": 36.5,
   "Texas": 40.5,
   "Creighton": 38.3,
   "St. Bonaventure": 15.4,
   "Oklahoma State": 37.6,
   "North Carolina": 12.5,
   "Maryland": 15.6,
   "LSU": 11.8,
   "Rutgers": 16.2,
   "Florida": 19.3,
   "Georgia Tech": 9.4,
   "Oregon": 15.6,
   "Utah State": 17.1,
   "Clemson": 12.2,
   "Syracuse": 17.2,
   "Virginia Tech": 13.5,
   "Oklahoma": 5.1,
   "VCU": 11.3,
   "Michigan State/UCLA": 15.6,
   "Missouri": 3.6,
   "Georgetown": 11.7,
   "Wichita State/Drake": 11.4,
   "North Texas": 9.0,
   "UC Santa Barbara": 10.2,
   "Oregon State": 9.4,
   "Ohio": 8.2,
   "Abilene Christian": 7.4,
   "Colgate": 6.3,
   "Liberty": 7.7,
   "UNC Greensboro": 4.7,
   "Winthrop": 5.0,
   "Eastern Washington": 3.7,
   "Grand Canyon": 2.5,
   "Morehead State": 2.9,
   "Cleveland State": 1.0,
   "Oral Roberts": 1.0,
   "Drexel": 0.5,
   "Iona": 0.4,
   "Hartford": 0.2,
   "Mount St. Mary's/Texas Southern": 0.11,
   "Norfolk State/Appalachian State": 0.04
    }
round_32_odds_2021 = {
   "Gonzaga": 99.6,
   "Illinois": 96.1,
   "Michigan": 98.4,
   "Baylor": 97.5,
   "Houston": 94.4,
   "Iowa": 91.0,
   "Ohio State": 93.8,
   "Alabama": 95.7,
   "Villanova": 80.7,
   "Loyola Chicago": 61.9,
   "Purdue": 72.6,
   "Florida State": 81.2,
   "Virginia": 74.3,
   "Arkansas": 78.1,
   "Tennessee": 73.0,
   "USC": 70.3,
   "Wisconsin": 56.4,
   "Colorado": 68.0,
   "San Diego State": 62.2,
   "Texas Tech": 60.5,
   "Connecticut": 57.4,
   "West Virginia": 84.1,
   "Kansas": 82.4,
   "BYU": 63.9,
   "Texas": 74.8,
   "Creighton": 70.9,
   "St. Bonaventure": 53.1,
   "Oklahoma State": 73.6,
   "North Carolina": 43.6,
   "Maryland": 42.6,
   "LSU": 46.9,
   "Rutgers": 54.6,
   "Florida": 55.6,
   "Georgia Tech": 38.1,
   "Oregon": 54.4,
   "Utah State": 39.5,
   "Clemson": 45.4,
   "Syracuse": 37.8,
   "Virginia Tech": 44.4,
   "Oklahoma": 53.6,
   "VCU": 45.6,
   "Michigan State/UCLA": 36.1,
   "Missouri": 46.4,
   "Georgetown": 32.0,
   "Wichita State/Drake": 29.6,
   "North Texas": 27.4,
   "UC Santa Barbara": 29.1,
   "Oregon State": 26.1,
   "Ohio": 25.7,
   "Abilene Christian": 25.2,
   "Colgate": 21.9,
   "Liberty": 26.4,
   "UNC Greensboro": 18.8,
   "Winthrop": 19.3,
   "Eastern Washington": 17.6,
   "Grand Canyon": 9.0,
   "Morehead State": 15.9,
   "Cleveland State": 5.6,
   "Oral Roberts": 6.2,
   "Drexel": 3.9,
   "Iona": 4.3,
   "Hartford": 2.5,
   "Mount St. Mary's/Texas Southern": 1.7,
   "Norfolk State/Appalachian State": 0.4
    }


odds_type = "percentage"
round_32_vig = 0.05 if odds_type == "american" else 0.0

## PAST AUCTION RESULTS
auction_results_2025 = {}
auction_results_2024 = {
    "Florida Atlantic": 975.00,
    "South Dakota State": 300.00,
    "Grand Canyon": 800.00,
    "Nevada": 1075.00,
    "Oakland": 400.00,
    "Boise State/Colorado": 1325.00,
    "Arizona": 7200.00,
    "Drake": 1025.00,
    "James Madison": 1050.00,
    "Long Beach State": 400.00,
    "Nebraska": 1100.00,
    "Dayton": 1125.00,
    "College of Charleston": 775.00,
    "Purdue": 9050.00,
    "Tennessee": 8050.00,
    "Stetson": 325.00,
    "Saint Mary's": 3350.00,
    "San Diego State": 2450.00,
    "Longwood": 450.00,
    "Mississippi State": 1325.00,
    "McNeese State": 1375.00,
    "Gonzaga": 3700.00,
    "Clemson": 1775.00,
    "Creighton": 5400.00,
    "Western Kentucky": 500.00,
    "Utah State": 1200.00,
    "NC State": 1200.00,
    "UNC": 8850.00,
    "Kentucky": 5475.00,
    "Texas": 1975.00,
    "Florida": 1875.00,
    "Akron": 700.00,
    "Auburn": 6350.00,
    "Iowa State": 7050.00,
    "Baylor": 5050.00,
    "Oregon": 1425.00,
    "Morehead State": 875.00,
    "Howard/Wagner": 400.00,
    "Washington State": 1700.00,
    "Connecticut": 12300.00,
    "Samford": 1025.00,
    "South Carolina": 1925.00,
    "Kansas": 2825.00,
    "TCU": 1700.00,
    "Virginia/Colorado State": 1500.00,
    "Texas A&M": 1750.00,
    "Wisconsin": 2550.00,
    "Yale": 700.00,
    "Duke": 5150.00,
    "Northwestern": 1275.00,
    "Michigan State": 2050.00,
    "New Mexico": 2125.00,
    "Houston": 11500.00,
    "Colgate": 575.00,
    "Montana State/Grambling": 500.00,
    "Vermont": 825.00,
    "BYU": 3625.00,
    "Duquesne": 650.00,
    "Illinois": 5200.00,
    "Saint Peter's": 525.00,
    "Alabama": 5275.00,
    "Texas Tech": 3350.00,
    "Marquette": 6150.00,
    "UAB": 1050.00
    }
auction_results_2023 = {
    "Louisiana": 575.00,
    "Howard": 225.00,
    "Michigan State": 1425.00,
    "Creighton": 2600.00,
    "Grand Canyon": 425.00,
    "USC": 975.00,
    "Connecticut": 3250.00,
    "Maryland": 950.00,
    "Saint Mary's": 925.00,
    "Duke": 3050.00,
    "Memphis": 1450.00,
    "Tennessee": 3450.00,
    "Oral Roberts": 775.00,
    "Marquette": 3075.00,
    "Providence": 975.00,
    "Montana State": 600.00,
    "Boise State": 1050.00,
    "Kansas State": 2550.00,
    "Kentucky": 1925.00,
    "Charleston": 975.00,
    "UCLA": 3025.00,
    "Vermont": 475.00,
    "Alabama": 6600.00,
    "Florida Atlantic": 1075.00,
    "Arkansas": 1325.00,
    "Virginia": 1975.00,
    "Missouri": 600.00,
    "Colgate": 550.00,
    "Drake": 600.00,
    "Gonzaga": 4025.00,
    "VCU": 1050.00,
    "Iona": 375.00,
    "Xavier": 2800.00,
    "Furman": 625.00,
    "Northwestern": 900.00,
    "Purdue": 4375.00,
    "Miami FL": 1550.00,
    "Texas A&M Corpus Chris": 275.00,
    "FDU/Texas Southern": 225.00,
    "Texas A&M": 1375.00,
    "West Virginia": 1000.00,
    "Nevada/Arizona State": 750.00,
    "Princeton": 525.00,
    "NC State": 825.00,
    "Houston": 5275.00,
    "Northern Kentucky": 425.00,
    "TCU": 1275.00,
    "Texas": 4950.00,
    "Auburn": 1150.00,
    "Arizona": 4250.00,
    "Kennesaw State": 450.00,
    "UNC Asheville": 475.00,
    "Iowa State": 1675.00,
    "Baylor": 3375.00,
    "Penn State": 900.00,
    "San Diego State": 2150.00,
    "Iowa": 975.00,
    "Pittsburgh": 825.00,
    "Indiana": 2175.00,
    "Kansas": 5775.00,
    "Kent State": 825.00,
    "Utah State": 1100.00,
    "UC Santa Barbara": 525.00,
    "Illinois": 925.00
    }
auction_results_2022 = {
    "Iowa State": 632.00,
    "Georgia State": 168.00,
    "South Dakota State": 601.00,
    "Rutgers/ND": 450.00,
    "Akron": 275.00,
    "Arkansas": 1475.00,
    "Vermont": 625.00,
    "Tennessee": 3900.00,
    "Murray State": 825.00,
    "New Mexico State": 600.00,
    "Cal State Fullerton": 300.00,
    "Houston": 3200.00,
    "Connecticut": 1925.00,
    "Illinois": 2250.00,
    "TCU": 750.00,
    "USC": 1000.00,
    "Kansas": 6100.00,
    "Indiana": 900.00,
    "Providence": 1325.00,
    "Marquette": 800.00,
    "San Francisco": 1075.00,
    "Wisconsin": 2375.00,
    "Richmond": 375.00,
    "LSU": 2025.00,
    "Ohio State": 1100.00,
    "Miami FL": 925.00,
    "Wright State": 250.00,
    "North Carolina": 1175.00,
    "Boise State": 700.00,
    "Seton Hall": 750.00,
    "Colorado State": 925.00,
    "Duke": 4025.00,
    "Virginia Tech": 1050.00,
    "UAB": 450.00,
    "Texas Southern": 250.00,
    "Saint Mary's": 1550.00,
    "Yale": 300.00,
    "Texas": 1350.00,
    "Memphis": 900.00,
    "Creighton": 725.00,
    "Gonzaga": 11725.00,
    "Davidson": 925.00,
    "Auburn": 5550.00,
    "Delaware": 275.00,
    "Jacksonville State": 325.00,
    "Norfolk State": 250.00,
    "UCLA": 4025.00,
    "Michigan State": 1025.00,
    "Arizona": 8000.00,
    "San Diego State": 950.00,
    "Michigan": 1500.00,
    "Colgate": 675.00,
    "Purdue": 3875.00,
    "Kentucky": 6050.00,
    "Longwood": 300.00,
    "Loyola Chicago": 1250.00,
    "Baylor": 5350.00,
    "Villanova": 5050.00,
    "Montana State": 350.00,
    "Alabama": 1375.00,
    "Saint Peter's": 325.00,
    "Chattanooga": 550.00,
    "Iowa": 4100.00,
    "Texas Tech": 4200.00
    }
auction_results_2021 = {
    "Loyola Chicago": 700,
    "Wichita State/Drake": 380,
    "Colorado": 1400,
    "Florida": 677,
    "Winthrop": 453,
    "Oral Roberts": 157,
    "Villanova": 1150,
    "Maryland": 750,
    "Purdue": 1900,
    "Oregon": 900,
    "Eastern Washington": 303,
    "Hartford": 179,
    "Texas Tech": 1650,
    "Houston": 4002,
    "USC": 1403,
    "Morehead State": 389,
    "Michigan State/UCLA": 955,
    "Syracuse": 655,
    "Utah State": 700,
    "Iowa": 4000,
    "VCU": 608,
    "Creighton": 1632,
    "Georgetown": 600,
    "Missouri": 525,
    "Rutgers": 1025,
    "Tennessee": 1601,
    "Oklahoma State": 1865,
    "Texas": 2565,
    "San Diego State": 1650,
    "Wisconsin": 1199,
    "Baylor": 6902,
    "Arkansas": 1956,
    "Drexel": 195,
    "BYU": 1250,
    "LSU": 1350,
    "Ohio": 675,
    "Virginia": 2078,
    "UC Santa Barbara": 675,
    "Kansas": 2450,
    "Michigan": 5600,
    "Colgate": 550,
    "St. Bonaventure": 950,
    "Alabama": 3729,
    "Mount St. Mary's/Texas Southern": 156,
    "Norfolk State/Appalachian State": 199,
    "Iona": 221,
    "Clemson": 850,
    "Abilene Christian": 387,
    "Cleveland State": 260,
    "Florida State": 2901,
    "Virginia Tech": 852,
    "Connecticut": 1700,
    "Gonzaga": 12200,
    "Oklahoma": 900,
    "North Texas": 645,
    "Illinois": 7755,
    "Ohio State": 4252,
    "Georgia Tech": 778,
    "West Virginia": 2608,
    "Oregon State": 628,
    "UNC Greensboro": 500,
    "Grand Canyon": 400,
    "Liberty": 707,
    "North Carolina": 1031
    }

auction_total_2024 = sum(auction_results_2024.values())
auction_total_2023 = sum(auction_results_2023.values())
auction_total_2022 = sum(auction_results_2022.values())
auction_total_2021 = sum(auction_results_2021.values())

past_pots = [auction_total_2021, auction_total_2022, auction_total_2023, auction_total_2024]


auction = CalcuttaAuction(
    past_pots, champ_odds_2024, second_place_odds_2024, final_four_odds_2024, elite_eight_odds_2024, sweet_sixteen_odds_2024, round_32_odds_2024, round_32_vig, team_seeds_2024, odds_type, auction_results_2025
)

initial_fair_values = auction.calculate_fair_value()
print(json.dumps({team: round(value, 2) for team, value in initial_fair_values.items()}, indent=2)) 
auction.run_live_update()  

#print(auction.past_auction_study(auction_results_2021, 2021))


